# Generated by Django 3.0.5 on 2020-05-17 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='playlist',
            name='unique playlist',
        ),
    ]
