# Generated by Django 3.0.5 on 2020-05-16 01:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=40, unique=True)),
                ('nickname', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=128, unique=True)),
                ('created_at', models.DateField(blank=True, default=django.utils.timezone.now, editable=False)),
                ('gender', models.CharField(blank=True, default='whatever', max_length=8)),
                ('year_birth', models.DateField(blank=True, null=True)),
                ('interests', models.TextField(blank=True, max_length=30, null=True)),
                ('bio', models.TextField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
