# Generated by Django 3.0.5 on 2020-05-17 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='created_at',
            field=models.DateField(editable=False, null=True),
        ),
    ]
